# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 "https://inh2613.github.io/"
baseurl:             "https://inh2613.github.io/"
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               "https://inh2613.github.io"
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
